name = "PorewaterDiffusion"
uuid = "c4f3a3d5-9d2b-45a9-ae02-31b9e0b08e88"
authors = ["Graham Harper Edwards", "Sarah Neuhaus"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
