name = "PorewaterDiffusion"
uuid = "c4f3a3d5-9d2b-45a9-ae02-31b9e0b08e88"
authors = ["Graham Harper Edwards", "Sarah U. Neuhaus"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DelimitedFiles = "1"
julia = "1.9"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs", "Suppressor"]
